### ISSUE TITLE
Tests failing, no releases

### ISSUE THREAD

**Issue by rfay** [hanoii/ddev-sshd#1]
Thanks for this, I know it's not intended to be available at this point.

Would you mind removing the `ddev-get` label from it so it's not discoverable?

Also, if it's going to get further progress, please get the tests going.

Thanks!

**Comment by hanoii** [comment]
What do you mean? I don't mind it being discoverable, I am supporting it

**Comment by rfay** [comment]
Right, but the tests are failing, and there are no releases. So `ddev get --list --all` gets it, but it can't be used with `ddev get`.

**Comment by hanoii** [comment]
I’ll create a release. It can be used with ddev get and the GitHub tarball

Reply might shorter than usual / Respuesta más resumida qué de costumbre
Enviado desde el celular / Sent from Mobile
